# Site settings
title: science tunnel
email: paul.adamson.01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Musings on quantum chemistry and data analytics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://padamson.github.io" # the base hostname & protocol for your site
twitter_username: pauleadamson
github_username:  padamson

timezone: America/New_York
highlighter: pygments # required to highlight chapel

# Build settings
markdown: kramdown
