# Site settings
title: truth tunnel
email: paul.adamson.01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tunneling to the truth of modeling systems of exotic particles, science code
  engineering, systems engineering, digitial photography, personal finance, and
  raising little hackers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://padamson.github.io" # the base hostname & protocol for your site
twitter_username: pauleadamson
github_username:  padamson

timezone: America/New_York
highlighter: pygments # required to highlight chapel

# Build settings
markdown: kramdown
