# Site settings
title: seeking eta
email: paul.adamson.01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes on seeking eta (efficiency, $\eta$) at the intersection of 
  science, computer programming, machine learning, and project management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://padamson.github.io" # the base hostname & protocol for your site
twitter_username: pauleadamson
github_username:  padamson
linkedin_username: pauleadamson
#facebook_username: dataprone

timezone: America/New_York
highlighter: rouge # required to highlight code

# Build settings
markdown: kramdown

gems:

quick_view_length: 200
