# Site settings
title: truth tunnel
email: paul.adamson.01@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
  Tunneling to the truth of modeling systems of exotic particles, science code
  engineering, systems engineering, digitial photography, personal finance, and
  raising little hackers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://padamson.github.io" # the base hostname & protocol for your site
twitter_username: pauleadamson
github_username:  padamson

timezone: America/New_York
highlighter: pygments # required to highlight chapel

# Build settings
markdown: kramdown
